package com.myfreeit.passwordgenerator;

/*
 * Copyright (c) 2024, Denis Odesskiy. All rights reserved.
 *
 * This software is the confidential and proprietary information of Denis Odesskiy
 * ("Confidential Information"). You shall not disclose such Confidential Information
 * and shall use it only in accordance with the terms of the license agreement you
 * entered into with Denis Odesskiy.
 */

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Set;

/**
 * The ModelUniquenessTest class contains unit tests for the {@link Model} class.
 *
 * <p>This class ensures that passwords generated by the {@link Model#generatePassword(int, boolean)}
 * method are unique over a large number of iterations. It checks the absence of duplicate
 * passwords during the generation process.</p>
 *
 * <p>The uniqueness of passwords is tested with a specific length and the option to include
 * or exclude special characters.</p>
 *
 * @author Denis Odesskiy
 * @since 2024
 */
class ModelUniquenessTest {

    /**
     * Tests the uniqueness of passwords generated without special characters.
     *
     * <p>This method generates 500,000 passwords of length 8 without special characters
     * and verifies that there are no duplicate passwords in the generated set. The test
     * will fail if any duplicates are found.</p>
     */
    @Test
    void testPasswordUniqueness() {
        Model model = new Model();
        int iterations = 500_000;
        int passwordLength = 8;
        boolean useSpecialChars = false;

        Set<String> generatedPasswords = new HashSet<>();

        int duplicateCount = 0;
        for (int i = 0; i < iterations; i++) {
            String password = model.generatePassword(passwordLength, useSpecialChars);
            if (!generatedPasswords.add(password)) {
                duplicateCount++;
            }
        }

        System.out.println("Password length: " + passwordLength + ", useSpecialChars: " + useSpecialChars);
        System.out.println("Total duplicates: " + duplicateCount);
        Assertions.assertEquals(0, duplicateCount, "Found duplicates: " + duplicateCount);
    }
}
